
import { ResgateFormData } from '@/schemas/resgateSchema';

export const defaultResgateForm: ResgateFormData = {
  data: '',
  horarioAcionamento: '',
  horarioTermino: '',
  regiaoAdministrativa: '',
  origem: '',
  desfechoResgate: '',
  latitudeOrigem: '',
  longitudeOrigem: '',
  desfechoApreensao: '',
  numeroTCO: '',
  outroDesfecho: '',
  estadoSaude: '',
  atropelamento: '',
  estagioVida: '',
  quantidadeAdulto: 0,
  quantidadeFilhote: 0,
  quantidade: 0,
  destinacao: '',
  numeroTermoEntrega: '',
  horaGuardaCEAPA: '',
  motivoEntregaCEAPA: '',
  latitudeSoltura: '',
  longitudeSoltura: '',
  outroDestinacao: '',
  classeTaxonomica: '',
  especieId: '',
  tipoAreaId: '',
};
