-- Insert teams from Equipes_BPMA.xlsx

-- GOC Teams
INSERT INTO dim_equipes (nome, grupamento, escala, servico) VALUES 
('ALFA', 'GOC', '24 X 72', 'OPERACIONAL'),
('BRAVO', 'GOC', '24 X 72', 'OPERACIONAL'),
('CHARLIE', 'GOC', '24 X 72', 'OPERACIONAL'),
('DELTA', 'GOC', '24 X 72', 'OPERACIONAL');

-- GTA Teams
INSERT INTO dim_equipes (nome, grupamento, escala, servico) VALUES 
('ALFA', 'GTA', '12 X 60', 'OPERACIONAL'),
('BRAVO', 'GTA', '12 X 60', 'OPERACIONAL'),
('CHARLIE', 'GTA', '12 X 60', 'OPERACIONAL');

-- LACUSTRE Teams
INSERT INTO dim_equipes (nome, grupamento, escala, servico) VALUES 
('ALFA', 'LACUSTRE', '24 X 72', 'OPERACIONAL'),
('BRAVO', 'LACUSTRE', '24 X 72', 'OPERACIONAL'),
('CHARLIE', 'LACUSTRE', '24 X 72', 'OPERACIONAL'),
('DELTA', 'LACUSTRE', '24 X 72', 'OPERACIONAL');

-- GUARDA Teams
INSERT INTO dim_equipes (nome, grupamento, escala, servico) VALUES 
('ALFA', 'GUARDA', '24 X 72', 'APOIO OPERACIONAL'),
('BRAVO', 'GUARDA', '24 X 72', 'APOIO OPERACIONAL'),
('CHARLIE', 'GUARDA', '24 X 72', 'APOIO OPERACIONAL'),
('DELTA', 'GUARDA', '24 X 72', 'APOIO OPERACIONAL');

-- ARMEIRO Teams (nested under GUARDA)
INSERT INTO dim_equipes (nome, grupamento, escala, servico) VALUES 
('ALFA', 'ARMEIRO', '24 X 72', 'APOIO OPERACIONAL'),
('BRAVO', 'ARMEIRO', '24 X 72', 'APOIO OPERACIONAL'),
('CHARLIE', 'ARMEIRO', '24 X 72', 'APOIO OPERACIONAL'),
('DELTA', 'ARMEIRO', '24 X 72', 'APOIO OPERACIONAL');

-- PATRULHA AMBIENTAL Teams
INSERT INTO dim_equipes (nome, grupamento, escala, servico) VALUES 
('ALFA', 'PATRULHA AMBIENTAL', '24 X 72', 'OPERACIONAL'),
('BRAVO', 'PATRULHA AMBIENTAL', '24 X 72', 'OPERACIONAL'),
('CHARLIE', 'PATRULHA AMBIENTAL', '24 X 72', 'OPERACIONAL'),
('DELTA', 'PATRULHA AMBIENTAL', '24 X 72', 'OPERACIONAL');

-- EXPEDIENTE (Administrative Sections)
INSERT INTO dim_equipes (nome, grupamento, escala, servico) VALUES 
('SECRETARIA', 'EXPEDIENTE', 'EXPEDIENTE', 'ADMINISTRATIVO'),
('SEÇÃO GARAGEM', 'EXPEDIENTE', 'EXPEDIENTE', 'ADMINISTRATIVO'),
('SEÇÃO PROJETOS', 'EXPEDIENTE', 'EXPEDIENTE', 'ADMINISTRATIVO'),
('SEÇÃO SECRIMPO', 'EXPEDIENTE', 'EXPEDIENTE', 'ADMINISTRATIVO'),
('SEÇÃO SJD', 'EXPEDIENTE', 'EXPEDIENTE', 'ADMINISTRATIVO'),
('SEÇÃO SLOG', 'EXPEDIENTE', 'EXPEDIENTE', 'ADMINISTRATIVO'),
('SEÇÃO SOI', 'EXPEDIENTE', 'EXPEDIENTE', 'ADMINISTRATIVO'),
('SEÇÃO SP', 'EXPEDIENTE', 'EXPEDIENTE', 'ADMINISTRATIVO'),
('SEÇÃO SVG', 'EXPEDIENTE', 'EXPEDIENTE', 'ADMINISTRATIVO');

-- OFICIAIS
INSERT INTO dim_equipes (nome, grupamento, escala, servico) VALUES 
('OFICIAIS ADM', 'OFICIAIS', 'EXPEDIENTE', 'ADMINISTRATIVO');

-- OFICIAIS OPERACIONAIS
INSERT INTO dim_equipes (nome, grupamento, escala, servico) VALUES 
('OFICIAL DE DIA', 'OFICIAIS OPERACIONAIS', '24 X 72', 'OPERACIONAL');

-- MANUTENÇÃO
INSERT INTO dim_equipes (nome, grupamento, escala, servico) VALUES 
('MANUTENÇÃO EMBARCAÇÕES', 'MANUTENÇÃO', '12 X 36', 'APOIO OPERACIONAL'),
('MANUTENÇÃO INSTALAÇÕES', 'MANUTENÇÃO', '12 X 36', 'APOIO OPERACIONAL');

-- MOTORISTAS
INSERT INTO dim_equipes (nome, grupamento, escala, servico) VALUES 
('MOTORISTA DE DIA', 'MOTORISTAS', '24 X 72', 'APOIO OPERACIONAL'),
('MOTORISTA DO CMT', 'MOTORISTAS', '12 X 36', 'APOIO OPERACIONAL');

-- INSTRUÇÕES E CURSO
INSERT INTO dim_equipes (nome, grupamento, escala, servico) VALUES 
('COORDENAÇÃO LACUSTRE', 'INSTRUÇÕES E CURSO', '12 X 36', 'APOIO OPERACIONAL'),
('INSTRUCAO CFP', 'INSTRUÇÕES E CURSO', '12 X 36', 'APOIO OPERACIONAL');

-- COMISSÕES
INSERT INTO dim_equipes (nome, grupamento, escala, servico) VALUES 
('CIP 12X36', 'COMISSÕES', '12 X 36', 'APOIO OPERACIONAL'),
('CIP ADM', 'COMISSÕES', 'EXPEDIENTE', 'ADMINISTRATIVO');

-- P2
INSERT INTO dim_equipes (nome, grupamento, escala, servico) VALUES 
('P2', 'P2', 'EXPEDIENTE', 'ADMINISTRATIVO');