-- OUTUBRO 2025
INSERT INTO fat_resgates_diarios_2025_especies (data_ocorrencia, mes, nome_popular, nome_cientifico, classe_taxonomica, quantidade_resgates, quantidade_solturas, quantidade_obitos, quantidade_feridos, quantidade_filhotes)
SELECT 
  '2025-10-01'::date,
  'Outubro',
  nome_popular,
  nome_cientifico,
  classe_taxonomica,
  SUM(quantidade_resgates),
  SUM(quantidade_solturas),
  SUM(quantidade_obitos),
  SUM(quantidade_feridos),
  SUM(quantidade_filhotes)
FROM (VALUES
  ('BEM-TE-VI', 'Pitangus sulphuratus', 'AVES', 8, 2, 0, 5, 2),
  ('CARCARÁ', 'Caracara plancus', 'AVES', 3, 1, 0, 2, 0),
  ('CORUJA BURAQUEIRA', 'Athene cunicularia', 'AVES', 12, 3, 0, 8, 1),
  ('CORUJA CABURÉ', 'Glaucidium brasilianum', 'AVES', 3, 0, 0, 2, 1),
  ('CORUJA ORELHUDA', 'Pseudoscops clamator', 'AVES', 2, 0, 0, 2, 0),
  ('CORUJA SUINDARA', 'Tyto furcata', 'AVES', 2, 0, 0, 2, 0),
  ('CORUJINHA DA MATA', 'Megascops choliba', 'AVES', 2, 0, 0, 1, 1),
  ('CURICACA', 'Theristicus caudatus', 'AVES', 2, 0, 0, 2, 0),
  ('CURIANGO', 'Nyctidromus albicollis', 'AVES', 1, 1, 0, 0, 0),
  ('FRANGO D''ÁGUA', 'Gallinula galeata', 'AVES', 2, 0, 0, 2, 0),
  ('JANDAIA', 'Aratinga jandaya', 'AVES', 2, 0, 0, 2, 0),
  ('JOÃO DE BARRO', 'Furnarius rufus', 'AVES', 2, 0, 0, 1, 0),
  ('JURUVA', 'Baryphthengus ruficapillus', 'AVES', 1, 0, 0, 1, 0),
  ('MARRECO', 'Anas platyrhynchos domesticus', 'AVES', 2, 0, 0, 2, 0),
  ('MARITACA', 'Pionus maximiliani', 'AVES', 4, 1, 0, 3, 0),
  ('MELRO', 'Turdus merula', 'AVES', 1, 0, 0, 0, 1),
  ('PAPAGAIO GALEGO', 'Alipiopsitta xanthops', 'AVES', 2, 0, 0, 2, 0),
  ('PAPAGAIO VERDADEIRO', 'Amazona aestiva', 'AVES', 4, 1, 0, 3, 0),
  ('PASSARO PRETO', 'Molothrus oryzivorus', 'AVES', 5, 0, 0, 2, 0),
  ('PERIQUITO DO ENCONTRO', 'Brotogeris chiriri', 'AVES', 22, 1, 0, 18, 3),
  ('PERIQUITO MARACANÃ', 'Psittacara leucophthalmus', 'AVES', 3, 0, 0, 3, 0),
  ('PERIQUITO RICO', 'Brotogeris tirica', 'AVES', 1, 0, 0, 1, 0),
  ('PICA-PAU', 'Campephilus robustus', 'AVES', 4, 0, 0, 3, 1),
  ('PINTASSILGO', 'Carduelis carduelis', 'AVES', 1, 0, 0, 1, 0),
  ('POMBA DO BANDO', 'Zenaida auriculata', 'AVES', 2, 1, 0, 1, 0),
  ('POMBA VERDADEIRA', 'Patagioenas picazuro', 'AVES', 1, 0, 0, 0, 1),
  ('QUERO-QUERO', 'Vanellus chilensis', 'AVES', 2, 0, 0, 1, 1),
  ('ROLINHA CINZENTA', 'Columbina passerina', 'AVES', 4, 1, 0, 2, 1),
  ('ROLINHA-ROXA', 'Columbina talpacoti', 'AVES', 2, 1, 0, 1, 0),
  ('SABIÁ BARRANCO', 'Turdus leucomelas', 'AVES', 3, 1, 0, 1, 0),
  ('SABIÁ-DO-CAMPO', 'Mimus saturninus', 'AVES', 2, 0, 0, 1, 1),
  ('SABIÁ LARANJEIRA', 'Turdus rufiventris', 'AVES', 5, 0, 0, 3, 1),
  ('SANHAÇO CINZENTO', 'Thraupis sayaca', 'AVES', 1, 0, 0, 1, 0),
  ('SARACURA', 'Aramides saracura', 'AVES', 2, 0, 0, 1, 1),
  ('SUIRIRI-CAVALEIRO', 'Tyrannidae', 'AVES', 1, 0, 0, 0, 0),
  ('TUCANO', 'Ramphastos toco', 'AVES', 3, 1, 0, 1, 1),
  ('URUBU', 'Coragyps atratus', 'AVES', 10, 5, 0, 3, 2),
  ('XEXÉU', 'Cacicus cela', 'AVES', 1, 0, 0, 1, 0),
  ('CACHORRO DO MATO', 'Cerdocyon thous', 'MAMÍFEROS', 1, 0, 0, 1, 0),
  ('CAPIVARA', 'Hydrochoerus hydrochaeris', 'MAMÍFEROS', 8, 5, 0, 3, 0),
  ('CUTIA', 'Dasyprocta leporina', 'MAMÍFEROS', 1, 1, 0, 0, 0),
  ('JAGUATIRICA', 'Leopardus pardalis', 'MAMÍFEROS', 1, 1, 0, 0, 0),
  ('LOBO GUARA', 'Chrysocyon brachyurus', 'MAMÍFEROS', 1, 1, 0, 0, 0),
  ('MACACO BUGIO/GUARIBA', 'Alouatta guariba', 'MAMÍFEROS', 1, 1, 0, 0, 0),
  ('MACACO PREGO', 'Cepajus robustus', 'MAMÍFEROS', 1, 0, 1, 0, 0),
  ('MACACO SAGUI', 'Callithrix jacchus', 'MAMÍFEROS', 3, 1, 0, 2, 0),
  ('MACACO SAGUI DO TUFO PRETO', 'Callithrix pennicillata', 'MAMÍFEROS', 5, 1, 0, 4, 0),
  ('MICO ESTRELA', 'Callithrix penicillata', 'MAMÍFEROS', 1, 0, 1, 0, 0),
  ('PORCO ESPINHO', 'Coendou prehensilis', 'MAMÍFEROS', 3, 2, 0, 1, 0),
  ('QUATI', 'Nasua nasua', 'MAMÍFEROS', 1, 0, 0, 0, 1),
  ('RAPOSA', 'Vulpes vulpes', 'MAMÍFEROS', 2, 0, 0, 2, 0),
  ('SARUÊ', 'Didelphis albiventris', 'MAMÍFEROS', 85, 55, 0, 12, 18),
  ('TAMANDUÁ MIRIM', 'Tamandua tetradactyla', 'MAMÍFEROS', 2, 2, 0, 0, 0),
  ('TATU GALINHA', 'Dasypus novemcinctus', 'MAMÍFEROS', 2, 1, 0, 1, 0),
  ('TATU PEBA', 'Euphractus sexcinctus', 'MAMÍFEROS', 2, 1, 0, 1, 0),
  ('VEADO CAMPEIRO', 'Ozotoceros bezoarticus', 'MAMÍFEROS', 1, 0, 0, 1, 0),
  ('CÁGADO COMUM', 'Mauremys leprosa', 'RÉPTEIS', 1, 0, 0, 1, 0),
  ('CÁGADO DE BARBICHA', 'Phrynops geoffroanus', 'RÉPTEIS', 2, 1, 0, 1, 0),
  ('IGUANA', 'Iguana iguana', 'RÉPTEIS', 1, 1, 0, 0, 0),
  ('JABUTI', 'Chelonoidis carbonaria', 'RÉPTEIS', 4, 3, 0, 0, 0),
  ('MINHOCUÇU', 'Rhinodrilus alatus', 'RÉPTEIS', 1, 1, 0, 0, 0),
  ('SERPENTE CASCAVEL', 'Crotalus durissus', 'RÉPTEIS', 8, 7, 0, 1, 0),
  ('SERPENTE COBRA CEGA / CECÍLIA', 'Gymnophiona', 'RÉPTEIS', 1, 1, 0, 0, 0),
  ('SERPENTE COBRA CEGA / DE DUAS CABEÇAS', 'Amphisbaenia', 'RÉPTEIS', 2, 2, 0, 0, 0),
  ('SERPENTE COBRA CIPÓ', 'Chironius bicarinatus', 'RÉPTEIS', 5, 5, 0, 0, 0),
  ('SERPENTE COBRA D''ÁGUA', 'Liophis typhlus', 'RÉPTEIS', 1, 1, 0, 0, 0),
  ('SERPENTE CORAL FALSA', 'Anilis scytale', 'RÉPTEIS', 3, 3, 0, 0, 0),
  ('SERPENTE CORAL VERDADEIRA', 'Micrurus lemniscatus', 'RÉPTEIS', 2, 2, 0, 0, 0),
  ('SERPENTE CORRE CAMPO', 'Thamnodynastes pallidus', 'RÉPTEIS', 6, 5, 0, 1, 0),
  ('SERPENTE JARARACA VERDADEIRA', 'Bothrops jararaca', 'RÉPTEIS', 4, 4, 0, 0, 0),
  ('SERPENTE JIBOIA', 'Boa constrictor', 'RÉPTEIS', 18, 16, 0, 2, 0),
  ('SERPENTE JIBOIA ARCO ÍRIS', 'Epicrates cenchria cenchria', 'RÉPTEIS', 2, 1, 0, 0, 0),
  ('TARTARUGA', 'Caretta caretta', 'RÉPTEIS', 1, 0, 0, 0, 0),
  ('TEIÚ', 'Tupinambis merianae', 'RÉPTEIS', 2, 2, 0, 0, 0)
) AS t(nome_popular, nome_cientifico, classe_taxonomica, quantidade_resgates, quantidade_solturas, quantidade_obitos, quantidade_feridos, quantidade_filhotes)
GROUP BY nome_popular, nome_cientifico, classe_taxonomica;

-- NOVEMBRO 2025
INSERT INTO fat_resgates_diarios_2025_especies (data_ocorrencia, mes, nome_popular, nome_cientifico, classe_taxonomica, quantidade_resgates, quantidade_solturas, quantidade_obitos, quantidade_feridos, quantidade_filhotes)
SELECT 
  '2025-11-01'::date,
  'Novembro',
  nome_popular,
  nome_cientifico,
  classe_taxonomica,
  SUM(quantidade_resgates),
  SUM(quantidade_solturas),
  SUM(quantidade_obitos),
  SUM(quantidade_feridos),
  SUM(quantidade_filhotes)
FROM (VALUES
  ('ARARA CANINDÉ', 'Ara ararauna', 'AVES', 1, 0, 0, 1, 0),
  ('BEM-TE-VI', 'Pitangus sulphuratus', 'AVES', 7, 1, 0, 5, 2),
  ('CARCARÁ', 'Caracara plancus', 'AVES', 2, 1, 0, 0, 0),
  ('CARDEAL-DO-NORDESTE', 'Paroaria dominicana', 'AVES', 5, 0, 0, 0, 0),
  ('COLEIRO', 'Sporophila caerulescens', 'AVES', 4, 0, 0, 0, 0),
  ('CORRUPIÃO', 'Icterus jamacaii', 'AVES', 3, 0, 0, 0, 0),
  ('CORUJA BURAQUEIRA', 'Athene cunicularia', 'AVES', 10, 2, 0, 7, 1),
  ('CORUJA CABURÉ', 'Glaucidium brasilianum', 'AVES', 2, 0, 0, 1, 1),
  ('CORUJA ORELHUDA', 'Pseudoscops clamator', 'AVES', 1, 0, 0, 1, 0),
  ('CURIÓ', 'Oryzoborus angolensis', 'AVES', 3, 0, 0, 0, 0),
  ('JANDAIA', 'Aratinga jandaya', 'AVES', 1, 0, 0, 1, 0),
  ('MARIA FACEIRA', 'Syrigma sibilatrix', 'AVES', 1, 0, 0, 0, 1),
  ('MARITACA', 'Pionus maximiliani', 'AVES', 4, 1, 0, 3, 0),
  ('PAPAGAIO GALEGO', 'Alipiopsitta xanthops', 'AVES', 2, 0, 0, 0, 0),
  ('PAPAGAIO VERDADEIRO', 'Amazona aestiva', 'AVES', 5, 2, 0, 3, 0),
  ('PASSARO PRETO', 'Molothrus oryzivorus', 'AVES', 4, 1, 0, 1, 0),
  ('PERIQUITO DO ENCONTRO', 'Brotogeris chiriri', 'AVES', 18, 1, 1, 14, 3),
  ('PERIQUITO MARACANÃ', 'Psittacara leucophthalmus', 'AVES', 3, 0, 0, 3, 0),
  ('PERIQUITO REI', 'Eupsittula aurea', 'AVES', 3, 1, 0, 2, 0),
  ('PICA-PAU', 'Campephilus robustus', 'AVES', 3, 0, 0, 3, 0),
  ('PINTASSILGO', 'Carduelis carduelis', 'AVES', 1, 0, 0, 0, 0),
  ('POMBA DO BANDO', 'Zenaida auriculata', 'AVES', 1, 0, 0, 1, 0),
  ('POMBA VERDADEIRA', 'Patagioenas picazuro', 'AVES', 1, 0, 0, 1, 0),
  ('QUERO-QUERO', 'Vanellus chilensis', 'AVES', 1, 0, 0, 0, 1),
  ('ROLINHA CINZENTA', 'Columbina passerina', 'AVES', 2, 0, 0, 2, 0),
  ('ROLINHA-ROXA', 'Columbina talpacoti', 'AVES', 2, 0, 0, 2, 0),
  ('SABIÁ BARRANCO', 'Turdus leucomelas', 'AVES', 3, 0, 0, 0, 0),
  ('SABIÁ-DO-CAMPO', 'Mimus saturninus', 'AVES', 3, 1, 0, 1, 1),
  ('SABIÁ LARANJEIRA', 'Turdus rufiventris', 'AVES', 4, 0, 1, 1, 1),
  ('SARACURA', 'Aramides saracura', 'AVES', 2, 0, 0, 0, 0),
  ('TICO TICO REI', 'Coryphospingus ptleatus', 'AVES', 2, 0, 0, 0, 0),
  ('TUCANO', 'Ramphastos toco', 'AVES', 2, 0, 0, 1, 1),
  ('URUBU', 'Coragyps atratus', 'AVES', 8, 4, 0, 2, 2),
  ('URUTAU', 'Nyctibius griseus', 'AVES', 2, 0, 0, 1, 0),
  ('MACACO BUGIO/GUARIBA', 'Alouatta guariba', 'MAMÍFEROS', 1, 0, 0, 1, 0),
  ('MACACO PREGO', 'Cepajus robustus', 'MAMÍFEROS', 1, 0, 1, 0, 0),
  ('MACACO SAGUI', 'Callithrix jacchus', 'MAMÍFEROS', 2, 0, 0, 1, 1),
  ('MACACO SAGUI DO TUFO PRETO', 'Callithrix pennicillata', 'MAMÍFEROS', 4, 0, 0, 4, 0),
  ('QUATI', 'Nasua nasua', 'MAMÍFEROS', 1, 1, 0, 0, 0),
  ('SARUÊ', 'Didelphis albiventris', 'MAMÍFEROS', 80, 50, 0, 12, 18),
  ('TAMANDUÁ MIRIM', 'Tamandua tetradactyla', 'MAMÍFEROS', 1, 1, 0, 0, 0),
  ('TATU GALINHA', 'Dasypus novemcinctus', 'MAMÍFEROS', 2, 0, 0, 2, 0),
  ('TATU PEBA', 'Euphractus sexcinctus', 'MAMÍFEROS', 1, 1, 0, 0, 0),
  ('CÁGADO COMUM', 'Mauremys leprosa', 'RÉPTEIS', 1, 1, 0, 0, 0),
  ('CÁGADO DE BARBICHA', 'Phrynops geoffroanus', 'RÉPTEIS', 2, 1, 0, 1, 0),
  ('JABUTI', 'Chelonoidis carbonaria', 'RÉPTEIS', 2, 2, 0, 0, 0),
  ('SERPENTE BOIPEBA', 'Xenodon merremii', 'RÉPTEIS', 1, 1, 0, 0, 0),
  ('SERPENTE CASCAVEL', 'Crotalus durissus', 'RÉPTEIS', 10, 9, 0, 0, 1),
  ('SERPENTE COBRA CEGA / DE DUAS CABEÇAS', 'Amphisbaenia', 'RÉPTEIS', 2, 2, 0, 0, 0),
  ('SERPENTE COBRA CIPÓ', 'Chironius bicarinatus', 'RÉPTEIS', 5, 5, 0, 0, 0),
  ('SERPENTE COBRA D''ÁGUA', 'Liophis typhlus', 'RÉPTEIS', 1, 1, 0, 0, 0),
  ('SERPENTE COBRA DORMIDEIRA', 'Sibynomorphus mikanii', 'RÉPTEIS', 2, 2, 0, 0, 0),
  ('SERPENTE COBRA-VERDE', 'Liophis typhlus', 'RÉPTEIS', 1, 1, 0, 0, 0),
  ('SERPENTE CORAL FALSA', 'Anilis scytale', 'RÉPTEIS', 3, 2, 0, 0, 1),
  ('SERPENTE CORAL VERDADEIRA', 'Micrurus lemniscatus', 'RÉPTEIS', 2, 2, 0, 0, 0),
  ('SERPENTE CORRE CAMPO', 'Thamnodynastes pallidus', 'RÉPTEIS', 4, 4, 0, 0, 0),
  ('SERPENTE JARARACA VERDADEIRA', 'Bothrops jararaca', 'RÉPTEIS', 4, 3, 0, 0, 1),
  ('SERPENTE JIBOIA', 'Boa constrictor', 'RÉPTEIS', 15, 13, 0, 2, 0),
  ('SERPENTE JIBOIA ARCO ÍRIS', 'Epicrates cenchria cenchria', 'RÉPTEIS', 2, 2, 0, 0, 0),
  ('SERPENTE MUÇURANA', 'Pseudoboa clelia', 'RÉPTEIS', 1, 1, 0, 0, 0),
  ('TARTARUGA TIGRE D''ÁGUA', 'Trachemys dorbigni', 'RÉPTEIS', 1, 0, 0, 1, 0),
  ('TEIÚ', 'Tupinambis merianae', 'RÉPTEIS', 1, 1, 0, 0, 0)
) AS t(nome_popular, nome_cientifico, classe_taxonomica, quantidade_resgates, quantidade_solturas, quantidade_obitos, quantidade_feridos, quantidade_filhotes)
GROUP BY nome_popular, nome_cientifico, classe_taxonomica;

-- DEZEMBRO 2025
INSERT INTO fat_resgates_diarios_2025_especies (data_ocorrencia, mes, nome_popular, nome_cientifico, classe_taxonomica, quantidade_resgates, quantidade_solturas, quantidade_obitos, quantidade_feridos, quantidade_filhotes)
SELECT 
  '2025-12-01'::date,
  'Dezembro',
  nome_popular,
  nome_cientifico,
  classe_taxonomica,
  SUM(quantidade_resgates),
  SUM(quantidade_solturas),
  SUM(quantidade_obitos),
  SUM(quantidade_feridos),
  SUM(quantidade_filhotes)
FROM (VALUES
  ('ARARA CANINDÉ', 'Ara ararauna', 'AVES', 2, 1, 0, 1, 0),
  ('BEM-TE-VI', 'Pitangus sulphuratus', 'AVES', 5, 0, 0, 4, 2),
  ('BICO DE PIMENTA', 'Saltator fuliginosus', 'AVES', 3, 0, 0, 0, 0),
  ('CABOCLINHO', 'Sporophila pileata', 'AVES', 1, 0, 0, 0, 0),
  ('CANÁRIO DA TERRA', 'Sicalis flaveola', 'AVES', 1, 0, 0, 1, 0),
  ('COLEIRO', 'Sporophila caerulescens', 'AVES', 4, 0, 0, 0, 0),
  ('CORUJA BURAQUEIRA', 'Athene cunicularia', 'AVES', 8, 2, 0, 5, 0),
  ('CORUJA CABURÉ', 'Glaucidium brasilianum', 'AVES', 1, 0, 0, 0, 0),
  ('CURICACA', 'Theristicus caudatus', 'AVES', 2, 0, 0, 1, 1),
  ('GAVIÃO CARIJO', 'Rupornis magnirostris', 'AVES', 2, 0, 0, 2, 0),
  ('GAVIÃO QUIRI QUIRI', 'Falco sparverius', 'AVES', 1, 0, 0, 1, 0),
  ('GARÇA BRANCA', 'Ardea alba', 'AVES', 1, 0, 0, 0, 0),
  ('FRANGO D''ÁGUA', 'Gallinula galeata', 'AVES', 1, 0, 0, 0, 0),
  ('MARITACA', 'Pionus maximiliani', 'AVES', 3, 0, 0, 1, 0),
  ('PAPAGAIO VERDADEIRO', 'Amazona aestiva', 'AVES', 4, 1, 0, 2, 0),
  ('PASSARO PRETO', 'Molothrus oryzivorus', 'AVES', 3, 0, 0, 0, 0),
  ('PATATIVA', 'Sporophila plumbea', 'AVES', 4, 0, 0, 0, 0),
  ('PERDIZ', 'Rhynchotus rufescens', 'AVES', 1, 1, 0, 0, 0),
  ('PERIQUITO DO ENCONTRO', 'Brotogeris chiriri', 'AVES', 15, 0, 0, 12, 3),
  ('PERIQUITO MARACANÃ', 'Psittacara leucophthalmus', 'AVES', 2, 0, 0, 0, 0),
  ('PERIQUITO REI', 'Eupsittula aurea', 'AVES', 1, 0, 0, 1, 0),
  ('PICA-PAU', 'Campephilus robustus', 'AVES', 2, 0, 0, 2, 0),
  ('POMBA VERDADEIRA', 'Patagioenas picazuro', 'AVES', 1, 0, 0, 1, 0),
  ('ROLINHA CINZENTA', 'Columbina passerina', 'AVES', 3, 0, 0, 2, 1),
  ('SABIÁ-DO-CAMPO', 'Mimus saturninus', 'AVES', 2, 0, 0, 1, 1),
  ('SANHAÇO CINZENTO', 'Thraupis sayaca', 'AVES', 1, 0, 0, 0, 0),
  ('TRINCA FERRO', 'Saltator maximus', 'AVES', 1, 0, 0, 0, 0),
  ('TIZIU', 'Volatinia jacarina', 'AVES', 1, 0, 0, 0, 0),
  ('TUCANO', 'Ramphastos toco', 'AVES', 2, 0, 0, 1, 1),
  ('URUBU', 'Coragyps atratus', 'AVES', 4, 1, 0, 0, 0),
  ('CAPIVARA', 'Hydrochoerus hydrochaeris', 'MAMÍFEROS', 8, 5, 0, 0, 0),
  ('FURÃO', 'Mustela putorius furo', 'MAMÍFEROS', 1, 0, 0, 0, 0),
  ('MACACO SAGUI', 'Callithrix jacchus', 'MAMÍFEROS', 2, 1, 0, 1, 0),
  ('MACACO SAGUI DO TUFO PRETO', 'Callithrix pennicillata', 'MAMÍFEROS', 3, 0, 0, 2, 0),
  ('PORCO ESPINHO', 'Coendou prehensilis', 'MAMÍFEROS', 2, 1, 0, 1, 0),
  ('SARUÊ', 'Didelphis albiventris', 'MAMÍFEROS', 75, 48, 1, 10, 16),
  ('TAMANDUÁ MIRIM', 'Tamandua tetradactyla', 'MAMÍFEROS', 1, 0, 0, 1, 0),
  ('CÁGADO DE BARBICHA', 'Phrynops geoffroanus', 'RÉPTEIS', 1, 0, 0, 1, 0),
  ('JABUTI', 'Chelonoidis carbonaria', 'RÉPTEIS', 2, 1, 0, 0, 0),
  ('SERPENTE CASCAVEL', 'Crotalus durissus', 'RÉPTEIS', 5, 4, 0, 0, 1),
  ('SERPENTE COBRA CIPÓ', 'Chironius bicarinatus', 'RÉPTEIS', 4, 4, 0, 0, 0),
  ('SERPENTE CORAL VERDADEIRA', 'Micrurus lemniscatus', 'RÉPTEIS', 1, 1, 0, 0, 0),
  ('SERPENTE CORRE CAMPO', 'Thamnodynastes pallidus', 'RÉPTEIS', 3, 2, 0, 0, 0),
  ('SERPENTE JARARACA VERDADEIRA', 'Bothrops jararaca', 'RÉPTEIS', 2, 2, 0, 0, 0),
  ('SERPENTE JIBOIA', 'Boa constrictor', 'RÉPTEIS', 12, 10, 0, 2, 0),
  ('SERPENTE JIBOIA ARCO ÍRIS', 'Epicrates cenchria cenchria', 'RÉPTEIS', 2, 1, 0, 0, 0),
  ('SERPENTE MUÇURANA', 'Pseudoboa clelia', 'RÉPTEIS', 1, 1, 0, 0, 0),
  ('TARTARUGA', 'Caretta caretta', 'RÉPTEIS', 1, 1, 0, 0, 0),
  ('TARTARUGA TIGRE D''ÁGUA', 'Trachemys dorbigni', 'RÉPTEIS', 1, 0, 0, 1, 0),
  ('TEIÚ', 'Tupinambis merianae', 'RÉPTEIS', 1, 1, 0, 0, 0)
) AS t(nome_popular, nome_cientifico, classe_taxonomica, quantidade_resgates, quantidade_solturas, quantidade_obitos, quantidade_feridos, quantidade_filhotes)
GROUP BY nome_popular, nome_cientifico, classe_taxonomica;