-- Inserir APMs do Distrito Federal (Competência Distrital)
INSERT INTO public.dim_area_especialmente_protegida (nome, competencia, tipo) VALUES
('APM Alagado', 'Distrital', 'APM'),
('APM Crispim', 'Distrital', 'APM'),
('APM Currais', 'Distrital', 'APM'),
('APM Engenho das Lajes', 'Distrital', 'APM'),
('APM Olho D''água', 'Distrital', 'APM'),
('APM Pedras', 'Distrital', 'APM'),
('APM Ponte de Terra', 'Distrital', 'APM'),
('APM Ribeirão do Gama', 'Distrital', 'APM'),
('APM Barrocão', 'Distrital', 'APM'),
('APM Capão da Onça', 'Distrital', 'APM'),
('APM Brejinho', 'Distrital', 'APM'),
('APM Contagem', 'Distrital', 'APM'),
('APM Corguinho', 'Distrital', 'APM'),
('APM Fumal', 'Distrital', 'APM'),
('APM Mestre D''Armas', 'Distrital', 'APM'),
('APM Paranoazinho', 'Distrital', 'APM'),
('APM Pipiripau', 'Distrital', 'APM'),
('APM Quinze', 'Distrital', 'APM'),
('APM São Bartolomeu (Parte Norte)', 'Distrital', 'APM'),
('APM São Bartolomeu (Parte Sul)', 'Distrital', 'APM'),
('APM Bananal', 'Distrital', 'APM'),
('APM Cabeça de Veado', 'Distrital', 'APM'),
('APM Cachoeirinha', 'Distrital', 'APM'),
('APM Santa Maria', 'Distrital', 'APM'),
('APM Taquari', 'Distrital', 'APM'),
('APM Torto', 'Distrital', 'APM'),
-- Inserir APPs (Áreas de Preservação Permanente)
('APP em margens de cursos d''água naturais (faixas marginais)', 'Distrital', 'APP'),
('APP no entorno de nascentes e olhos d''água perenes', 'Distrital', 'APP'),
('APP no entorno de lagos e lagoas naturais', 'Distrital', 'APP'),
('APP no entorno de reservatórios artificiais (quando aplicável)', 'Distrital', 'APP'),
('APP em veredas e outras áreas úmidas protegidas', 'Distrital', 'APP'),
('APP em encostas íngremes, topo de morro e outras situações geomorfológicas previstas na lei', 'Distrital', 'APP')
ON CONFLICT DO NOTHING;