-- Inserir todos os tipos penais
INSERT INTO public.dim_tipo_penal (nome) VALUES
('Abandono De Função'),
('Abandono De Incapaz'),
('Abandono Intelectual'),
('Abandono Material'),
('Aborto'),
('Abuso De Autoridade'),
('Abuso De Incapazes'),
('Adulteração De Sinal Identificador De Veículo Automotor'),
('Advocacia Administrativa'),
('Aliciamento De Trabalhadores De Um Local Para Outro Do Território Nacional'),
('Aliciamento Para O Fim De Emigração'),
('Alienação Ou Oneração Fraudulenta De Coisa Própria'),
('Alteração De Limites'),
('Ameaça'),
('Ameaça De Bomba'),
('Anúncio De Meio Abortivo'),
('Apologia De Crime Ou Criminoso'),
('Apropriação De Coisa Achada'),
('Apropriação De Coisa Havida Por Erro, Caso Fortuito Ou Força Da Natureza'),
('Apropriação De Tesouro'),
('Apropriação Indébita'),
('Apropriação Indébita Previdenciária'),
('Arrebatamento De Preso'),
('Arremesso De Projétil'),
('Arremesso Ou Colocação Perigosa'),
('Assédio Sexual'),
('Associação Criminosa'),
('Associação Para O Fim De Tráfico De Substância Entorpecente'),
('Associação Secreta'),
('Assunção De Obrigação No Último Ano Do Mandato Ou Legislatura'),
('Atendimento Clínico'),
('Atentado Ao Pudor Mediante Fraude'),
('Atentado Contra A Liberdade De Associação'),
('Atentado Contra A Liberdade De Contrato De Trabalho E Boicotagem Violenta'),
('Atentado Contra A Liberdade De Trabalho'),
('Atentado Contra A Segurança De Outro Meio De Transporte'),
('Atentado Contra A Segurança De Serviço De Utilidade Pública'),
('Atentado Contra A Segurança De Transporte Marítimo, Fluvial Ou Aéreo'),
('Atentado Violento Ao Pudor'),
('Ato Obsceno'),
('Auto-Acusação Falsa'),
('Autuação De Trânsito'),
('Bigamia'),
('Calúnia'),
('Casa De Prostituição'),
('Certidão Ou Atestado Ideologicamente Falso'),
('Charlatanismo'),
('Coação Em Curso De Processo'),
('Comércio Ilegal De Arma De Fogo'),
('Comunicação Falsa De Crime Ou De Contravenção'),
('Concussão'),
('Condescendência Criminosa'),
('Constrangimento Ilegal'),
('Contrabando Ou Descaminho'),
('Corrida, Disputa Ou Competição Automobilística'),
('Corrupção Ativa'),
('Corrupção Ativa Em Transação Comercial Internacional'),
('Corrupção De Menores'),
('Corrupção Passiva'),
('Corrupção Ou Poluição De Água Potável'),
('Desacato'),
('Descumprimento De Medidas Protetivas De Urgência'),
('Desobediência'),
('Desobediência À Decisão Judicial Sobre Perda Ou Suspensão De Direito'),
('Desobediência À Medida Judicial Protetiva'),
('Destruição, Subtração Ou Ocultação De Cadáver'),
('Difamação'),
('Difusão De Doença Ou Praga'),
('Direção Perigosa De Veículo Na Via Pública'),
('Dirigir Veículo Automotor Em Via Pública Sem Permissão Para Dirigir Ou Habilitação Ou Cassado O Direito De Dirigir Gerando Perigo De Dano'),
('Discriminação'),
('Disparo De Arma De Fogo'),
('Disposição De Coisa Alheia Como Própria'),
('Divulgação De Segredo'),
('Duplicata Simulada'),
('Embriaguez Ao Volante'),
('Emissão De Título Ao Portador Sem Permissão Legal'),
('Emprego De Processo Proibido Ou De Substância Não Permitida'),
('Emprego Irregular De Verbas Ou Rendas Públicas'),
('Entrega De Direção A Inabilitado'),
('Entrega De Filho Menor A Pessoa Inidônea'),
('Envenenamento De Água Potável Ou De Substância Alimentícia Ou Medicinal'),
('Envenenamento Por Alimento'),
('Envenenamento Por Droga'),
('Envenenamento Por Fumaça'),
('Envenenamento Por Gás'),
('Envenenamento Por Medicamento'),
('Epidemia'),
('Esbulho Possessório'),
('Estelionato'),
('Estupro'),
('Estupro (Tentativa)'),
('Evasão Do Local De Acidente De Trânsito'),
('Evasão Mediante Violência Contra A Pessoa'),
('Exercício Arbitrário Das Próprias Razões'),
('Exercício Arbitrário Ou Abuso De Poder'),
('Exercício De Atividade Com Infração De Decisão Administrativa'),
('Exercício Ilegal Da Medicina, Arte Dentária Ou Farmacêutica'),
('Exercício Ilegal De Profissão Ou Atividade'),
('Exercício Ilegal Do Comércio De Coisas Antigas E Obras De Arte'),
('Exploração De Trabalho Infantil'),
('Explosão'),
('Explosão De Caixa Eletrônico'),
('Extorsão'),
('Extorsão Indireta'),
('Extorsão Mediante Sequestro'),
('Extravio'),
('Extravio De Arma De Fogo'),
('Extravio, Sonegação Ou Inutilização De Livro Ou Documento'),
('Fábrico, Comércio Ou Detenção De Arma'),
('Fabrico, Fornecimento, Aquisição, Posse Ou Transporte De Explosivos Ou Gás Tóxico, Ou Asfixiante'),
('Facilitação De Contrabando Ou Descaminho'),
('Falsa Identidade'),
('Falsidade De Atestado Médico'),
('Falsidade Ideológica'),
('Falsidade Material De Atestado Ou Certidão'),
('Falsificação De Documento Particular'),
('Falsificação De Documento Público'),
('Falsificação De Papéis Públicos'),
('Falsificação De Selo Ou Sinal Público'),
('Falsificação Do Sinal Empregado No Contraste De Metal Precioso Ou Na Fiscalização Alfandegária, Ou Para Outros Fins'),
('Falsificação, Corrupção, Adulteração Ou Alteração De Produto Destinado A Fins Terapêuticos Ou Medicinais'),
('Falsificação, Corrupção, Adulteração Ou Alteração De Substância Ou Produtos Alimentícios'),
('Falso Testemunho Ou Falsa Perícia'),
('Favorecimento Da Prostituição'),
('Favorecimento Pessoal'),
('Favorecimento Real'),
('Feminicídio'),
('Feminicídio - Tentativa'),
('Fingir-Se Funcionário Público'),
('Fraude À Execução'),
('Fraude De Lei Sobre Estrangeiro'),
('Fraude Na Entrega Da Coisa'),
('Fraude No Comércio'),
('Fraude No Pagamento Por Meio De Cheque'),
('Fraude Para Recebimento De Indenização Ou Valor De Seguro'),
('Fraude Processual'),
('Fraudes E Abusos Na Fundação Ou Administração De Sociedade Por Ações'),
('Frustração De Direito Assegurado Por Lei Trabalhista'),
('Frustração De Lei Sobre A Nacionalização Do Trabalho'),
('Fuga De Pessoa Presa Ou Submetida A Medida De Segurança'),
('Fuga De Preso'),
('Furto (Tentativa)'),
('Furto A Transeunte'),
('Furto De Água, Energia E Sinal Telefônico'),
('Furto De Animal'),
('Furto De Arma De Fogo'),
('Furto De Bicicleta'),
('Furto De Cabos De Transmissão De Dados, Telefonia E Energia'),
('Furto De Celular'),
('Furto De Ciclomotor'),
('Furto De Motocicleta'),
('Furto De Veículo'),
('Homicídio'),
('Homicídio (Tentativa)'),
('Homicídio Culposo'),
('Impedimento Ou Perturbação De Cerimônia Funerária'),
('Impedimento, Perturbação Ou Fraude De Concorrência'),
('Importunação Ofensiva Ao Pudor'),
('Incitação Ao Crime'),
('Induzimento A Erro Essencial E Ocultação De Impedimento'),
('Induzimento A Fuga, Entrega Arbitrária Ou Sonegação De Incapazes'),
('Induzimento, Instigação Ou Auxílio Ao Suicídio'),
('Infanticídio'),
('Infração De Medida Sanitária Preventiva'),
('Injúria'),
('Injúria Racial'),
('Inscrição De Despesas Não Empenhadas Em Restos A Pagar'),
('Inserção De Dados Falsos Em Sistema De Informações'),
('Instrumento De Emprego Usual Na Prática De Furto'),
('Interceptação Telefônica Sem Autorização'),
('Internação Irregular Em Estabelecimento Psiquiátrico'),
('Interrupção Ou Perturbação De Serviço Telegráfico Ou Telefônico'),
('Intimidação Sistemática (Bullying)'),
('Intimidação Sistemática Virtual (Cyberbullying)'),
('Inumação Ou Exumação De Cadáver'),
('Inutilização De Edital Ou De Sinal'),
('Jogo De Azar'),
('Jogo Do Bicho'),
('Latrocínio'),
('Latrocínio - Tentado'),
('Lavagem De Dinheiro'),
('Lesão Corporal'),
('Lesão Corporal Culposa'),
('Lesão Corporal De Natureza Grave/Gravíssima'),
('Lesão Corporal Recíproca'),
('Lesão Corporal Seguida De Morte'),
('Localização De Artefato Explosivo'),
('Mandado De Prisão'),
('Maus-Tratos'),
('Maus-Tratos A Animais'),
('Mediação Para Servir A Lascívia De Outrem'),
('Medicamento Em Desacordo Com Receita Médica'),
('Modificação Ou Alteração Não Autorizada De Sistema De Informações'),
('Moeda Falsa'),
('Morte A Esclarecer'),
('Não Cancelamento De Restos A Pagar'),
('Omissão De Cautela'),
('Omissão De Cautela Na Guarda Ou Condução De Animais'),
('Omissão De Comunicação De Crime'),
('Omissão De Notificação De Doença'),
('Omissão De Socorro'),
('Ordenação De Despesas Não Autorizada'),
('Organização Criminosa'),
('Parcelamento Irregular Do Solo'),
('Patrocínio Infiel'),
('Peculato'),
('Peculato Mediante Erro De Outrem'),
('Perigo De Contágio De Moléstia Grave'),
('Perigo De Contágio Venéreo'),
('Perturbação Da Tranquilidade'),
('Perturbação Do Trabalho Ou Do Sossego Alheios'),
('Petrechos De Falsificação'),
('Petrechos Para Falsificação De Moeda'),
('Pichação'),
('Porte De Arma Branca'),
('Porte Ilegal De Arma De Fogo De Uso Permitido, Acessório Ou Munição'),
('Posse Irregular De Arma De Fogo De Uso Permitido, Acessório Ou Munição'),
('Posse Não Justificada De Instrumento De Emprego Usual Na Prática De Furto'),
('Posse Ou Porte Ilegal De Arma De Fogo De Uso Restrito, Acessório Ou Munição'),
('Posse Sexual Mediante Fraude'),
('Preconceito De Raça, Cor, Etnia, Religião Ou Procedência Nacional'),
('Prevaricação'),
('Prevenção'),
('Prevenção De Acidente Automobilístico'),
('Prevenção De Artefato Explosivo'),
('Prevenção De Desabamento'),
('Prevenção De Desmoronamento'),
('Prevenção De Produtos Perigosos'),
('Prevenção De Rescaldo'),
('Prevenção Em Acampamento'),
('Prevenção Em Aeroporto'),
('Prevenção Em Autódromo'),
('Prevenção Em Ciclódromo'),
('Prevenção Em Cinema'),
('Prevenção Em Circo'),
('Prevenção Em Clube'),
('Prevenção Em Desfile'),
('Prevenção Em Destelhamento'),
('Prevenção Em Edifício Comercial'),
('Prevenção Em Estabelecimento De Ensino'),
('Prevenção Em Eventos Esportivos'),
('Prevenção Em Eventos Religiosos'),
('Prevenção Em Feiras E Exposições'),
('Prevenção Em Funeral'),
('Prevenção Em Ginásio'),
('Prevenção Em Hipódromo'),
('Prevenção Em Hospital'),
('Prevenção Em Kartódromo'),
('Prevenção Em Motódromo'),
('Prevenção Em Órgão Público'),
('Prevenção Em Parque De Diversões'),
('Prevenção Em Parque Recreativo'),
('Prevenção Em Passeatas'),
('Prevenção Em Pontos De Demonstração'),
('Prevenção Em Posto De Gasolina'),
('Prevenção Em Presídio'),
('Prevenção Em Residência'),
('Prevenção Em Rio'),
('Prevenção Em Rodovia'),
('Prevenção Em Rua De Lazer'),
('Prevenção Em Shows'),
('Prevenção Em Simulado'),
('Prevenção Em Stand De Tiro'),
('Prevenção Em Via Pública'),
('Prevenção Em Zoológico'),
('Prevenção No Lago'),
('Provocação De Tumulto'),
('Quadrilha Ou Bando'),
('Queima De Fogos De Artifício Ou Soltar Balão Aceso'),
('Racismo'),
('Receptação'),
('Receptação Culposa'),
('Receptação Qualificada'),
('Recusa De Dados Sobre A Própria Identidade Ou Qualificação'),
('Redução A Condição Análoga À De Escravo'),
('Registro De Nascimento Inexistente'),
('Reingresso De Estrangeiro Expulso'),
('Resistência'),
('Rixa'),
('Roubo (Tentativa)'),
('Roubo A Banco'),
('Roubo A Transeunte'),
('Roubo Com Restrição De Liberdade Da Vítima Em Concurso Com Extorsão'),
('Roubo De Carga'),
('Roubo De Veículo'),
('Rufianismo'),
('Sequestro E Cárcere Privado'),
('Simulação Da Qualidade De Funcionário'),
('Simulação De Autoridade Para Celebração De Casamento'),
('Sonegação De Contribuição Previdenciária'),
('Sonegação De Estado De Filiação'),
('Sonegação De Papel Ou Objeto De Valor Probatório'),
('Sonegação Ou Destruição De Correspondência'),
('Subtração De Incapazes'),
('Subtração Ou Inutilização De Livro Ou Documento'),
('Supressão De Documento'),
('Supressão Ou Alteração De Marca Em Animais'),
('Tráfico De Influência'),
('Tráfico De Influência Em Transação Comercial Internacional'),
('Tráfico De Substância Entorpecente'),
('Tráfico De Substância Entorpecente Prevalecendo-Se Da Função Pública'),
('Tráfico Internacional De Arma De Fogo'),
('Tráfico Internacional De Substância Entorpecente'),
('Uso De Documento Falso'),
('Uso De Gás Tóxico Ou Asfixiante'),
('Uso E Porte De Substância Entorpecente'),
('Uso Ilegítimo De Uniforme Ou Distintivo'),
('Usurpação De Função Pública'),
('Vadiagem'),
('Vender Substância Entorpecente Para Menor'),
('Violação De Correspondência'),
('Violação De Direito Autoral'),
('Violação De Domicílio'),
('Violação De Segredo Profissional'),
('Violação De Sepultura'),
('Violação De Sigilo Funcional'),
('Violência Arbitrária'),
('Vilipêndio A Cadáver'),
('Vias De Fato')
ON CONFLICT (nome) DO NOTHING;