-- JULHO 2025
INSERT INTO fat_resgates_diarios_2025_especies (data_ocorrencia, mes, nome_popular, nome_cientifico, classe_taxonomica, quantidade_resgates, quantidade_solturas, quantidade_obitos, quantidade_feridos, quantidade_filhotes)
SELECT 
  '2025-07-01'::date,
  'Julho',
  nome_popular,
  nome_cientifico,
  classe_taxonomica,
  SUM(quantidade_resgates),
  SUM(quantidade_solturas),
  SUM(quantidade_obitos),
  SUM(quantidade_feridos),
  SUM(quantidade_filhotes)
FROM (VALUES
  ('ARARA CANINDÉ', 'Ara ararauna', 'AVES', 1, 0, 0, 1, 0),
  ('CORUJA BURAQUEIRA', 'Athene cunicularia', 'AVES', 8, 1, 0, 6, 0),
  ('CORUJA ORELHUDA', 'Pseudoscops clamator', 'AVES', 2, 0, 0, 2, 0),
  ('CORUJA SUINDARA', 'Tyto furcata', 'AVES', 2, 0, 0, 2, 0),
  ('CORUJINHA DA MATA', 'Megascops choliba', 'AVES', 1, 0, 0, 0, 1),
  ('CURICACA', 'Theristicus caudatus', 'AVES', 1, 0, 0, 1, 0),
  ('GAVIÃO CARIJO', 'Rupornis magnirostris', 'AVES', 1, 0, 0, 1, 0),
  ('GAVIÃO QUIRI QUIRI', 'Falco sparverius', 'AVES', 1, 0, 0, 1, 0),
  ('JOÃO DE BARRO', 'Furnarius rufus', 'AVES', 2, 0, 0, 1, 1),
  ('MARRECO', 'Anas platyrhynchos domesticus', 'AVES', 2, 0, 0, 2, 0),
  ('PAPAGAIO VERDADEIRO', 'Amazona aestiva', 'AVES', 1, 0, 0, 1, 0),
  ('PERIQUITO DO ENCONTRO', 'Brotogeris chiriri', 'AVES', 8, 0, 0, 6, 2),
  ('PERIQUITO MARACANÃ', 'Psittacara leucophthalmus', 'AVES', 2, 0, 0, 2, 0),
  ('PICA-PAU', 'Campephilus robustus', 'AVES', 4, 0, 0, 4, 0),
  ('POMBA DO BANDO', 'Zenaida auriculata', 'AVES', 1, 0, 0, 1, 0),
  ('QUERO-QUERO', 'Vanellus chilensis', 'AVES', 3, 1, 0, 0, 2),
  ('ROLINHA CINZENTA', 'Columbina passerina', 'AVES', 2, 0, 0, 2, 0),
  ('SABIÁ LARANJEIRA', 'Turdus rufiventris', 'AVES', 1, 0, 0, 1, 0),
  ('SARACURA', 'Aramides saracura', 'AVES', 2, 0, 0, 1, 1),
  ('TUCANO', 'Ramphastos toco', 'AVES', 1, 0, 0, 1, 0),
  ('URUBU', 'Coragyps atratus', 'AVES', 4, 1, 0, 2, 0),
  ('URUTAU', 'Nyctibius griseus', 'AVES', 2, 1, 0, 1, 0),
  ('CAPIVARA', 'Hydrochoerus hydrochaeris', 'MAMÍFEROS', 5, 3, 0, 2, 0),
  ('FURÃO', 'Mustela putorius furo', 'MAMÍFEROS', 1, 1, 0, 0, 0),
  ('MACACO SAGUI', 'Callithrix jacchus', 'MAMÍFEROS', 2, 0, 0, 2, 0),
  ('MACACO SAGUI DO TUFO PRETO', 'Callithrix pennicillata', 'MAMÍFEROS', 3, 0, 0, 3, 0),
  ('PORCO ESPINHO', 'Coendou prehensilis', 'MAMÍFEROS', 2, 1, 0, 1, 0),
  ('RAPOSA', 'Vulpes vulpes', 'MAMÍFEROS', 1, 1, 0, 0, 0),
  ('SARUÊ', 'Didelphis albiventris', 'MAMÍFEROS', 45, 25, 0, 8, 10),
  ('TAMANDUÁ MIRIM', 'Tamandua tetradactyla', 'MAMÍFEROS', 1, 0, 0, 1, 0),
  ('TATU GALINHA', 'Dasypus novemcinctus', 'MAMÍFEROS', 2, 1, 0, 1, 0),
  ('CÁGADO COMUM', 'Mauremys leprosa', 'RÉPTEIS', 1, 1, 0, 0, 0),
  ('CÁGADO DE BARBICHA', 'Phrynops geoffroanus', 'RÉPTEIS', 1, 0, 0, 1, 0),
  ('JABUTI', 'Chelonoidis carbonaria', 'RÉPTEIS', 2, 2, 0, 0, 0),
  ('SERPENTE CASCAVEL', 'Crotalus durissus', 'RÉPTEIS', 3, 3, 0, 0, 0),
  ('SERPENTE COBRA CIPÓ', 'Chironius bicarinatus', 'RÉPTEIS', 3, 3, 0, 0, 0),
  ('SERPENTE CORAL FALSA', 'Anilis scytale', 'RÉPTEIS', 1, 1, 0, 0, 0),
  ('SERPENTE CORAL VERDADEIRA', 'Micrurus lemniscatus', 'RÉPTEIS', 1, 1, 0, 0, 0),
  ('SERPENTE CORRE CAMPO', 'Thamnodynastes pallidus', 'RÉPTEIS', 2, 2, 0, 0, 0),
  ('SERPENTE JIBOIA', 'Boa constrictor', 'RÉPTEIS', 8, 8, 0, 0, 0)
) AS t(nome_popular, nome_cientifico, classe_taxonomica, quantidade_resgates, quantidade_solturas, quantidade_obitos, quantidade_feridos, quantidade_filhotes)
GROUP BY nome_popular, nome_cientifico, classe_taxonomica;

-- AGOSTO 2025
INSERT INTO fat_resgates_diarios_2025_especies (data_ocorrencia, mes, nome_popular, nome_cientifico, classe_taxonomica, quantidade_resgates, quantidade_solturas, quantidade_obitos, quantidade_feridos, quantidade_filhotes)
SELECT 
  '2025-08-01'::date,
  'Agosto',
  nome_popular,
  nome_cientifico,
  classe_taxonomica,
  SUM(quantidade_resgates),
  SUM(quantidade_solturas),
  SUM(quantidade_obitos),
  SUM(quantidade_feridos),
  SUM(quantidade_filhotes)
FROM (VALUES
  ('BEM-TE-VI', 'Pitangus sulphuratus', 'AVES', 4, 0, 0, 4, 0),
  ('CORUJA BURAQUEIRA', 'Athene cunicularia', 'AVES', 6, 0, 0, 6, 0),
  ('CORUJA ORELHUDA', 'Pseudoscops clamator', 'AVES', 1, 0, 0, 1, 0),
  ('CURICACA', 'Theristicus caudatus', 'AVES', 2, 0, 0, 2, 0),
  ('CURIANGO', 'Nyctidromus albicollis', 'AVES', 2, 1, 0, 0, 1),
  ('FRANGO D''ÁGUA', 'Gallinula galeata', 'AVES', 1, 0, 0, 1, 0),
  ('GAVIÃO QUIRI QUIRI', 'Falco sparverius', 'AVES', 2, 1, 0, 1, 0),
  ('JANDAIA', 'Aratinga jandaya', 'AVES', 1, 0, 0, 1, 0),
  ('JOÃO DE BARRO', 'Furnarius rufus', 'AVES', 3, 0, 0, 2, 1),
  ('MARRECO', 'Anas platyrhynchos domesticus', 'AVES', 5, 0, 0, 5, 0),
  ('MARITACA', 'Pionus maximiliani', 'AVES', 3, 0, 0, 2, 1),
  ('PAPAGAIO VERDADEIRO', 'Amazona aestiva', 'AVES', 2, 1, 0, 1, 0),
  ('PERIQUITO DO ENCONTRO', 'Brotogeris chiriri', 'AVES', 10, 0, 0, 8, 2),
  ('PICA-PAU', 'Campephilus robustus', 'AVES', 3, 0, 0, 2, 1),
  ('POMBA DO BANDO', 'Zenaida auriculata', 'AVES', 1, 0, 0, 1, 0),
  ('POMBA VERDADEIRA', 'Patagioenas picazuro', 'AVES', 2, 0, 0, 1, 1),
  ('QUERO-QUERO', 'Vanellus chilensis', 'AVES', 2, 0, 0, 0, 2),
  ('ROLINHA CINZENTA', 'Columbina passerina', 'AVES', 2, 0, 0, 1, 1),
  ('SABIÁ BARRANCO', 'Turdus leucomelas', 'AVES', 1, 0, 0, 1, 0),
  ('SABIÁ LARANJEIRA', 'Turdus rufiventris', 'AVES', 3, 0, 0, 2, 1),
  ('SERIEMA', 'Cariama cristata', 'AVES', 1, 1, 0, 0, 0),
  ('TUCANO', 'Ramphastos toco', 'AVES', 1, 0, 0, 1, 0),
  ('URUBU', 'Coragyps atratus', 'AVES', 3, 2, 0, 1, 0),
  ('URUTAU', 'Nyctibius griseus', 'AVES', 1, 1, 0, 0, 0),
  ('CAPIVARA', 'Hydrochoerus hydrochaeris', 'MAMÍFEROS', 4, 2, 0, 2, 0),
  ('CUICA VERDADEIRO', 'Philander opossum', 'MAMÍFEROS', 1, 0, 0, 0, 1),
  ('MACACO SAGUI', 'Callithrix jacchus', 'MAMÍFEROS', 2, 1, 0, 1, 0),
  ('MACACO SAGUI DO TUFO PRETO', 'Callithrix pennicillata', 'MAMÍFEROS', 2, 0, 0, 2, 0),
  ('PORCO ESPINHO', 'Coendou prehensilis', 'MAMÍFEROS', 2, 1, 0, 1, 0),
  ('SARUÊ', 'Didelphis albiventris', 'MAMÍFEROS', 42, 30, 0, 5, 6),
  ('TAMANDUÁ MIRIM', 'Tamandua tetradactyla', 'MAMÍFEROS', 1, 1, 0, 0, 0),
  ('TATU GALINHA', 'Dasypus novemcinctus', 'MAMÍFEROS', 2, 0, 0, 1, 1),
  ('JABUTI', 'Chelonoidis carbonaria', 'RÉPTEIS', 2, 1, 0, 1, 0),
  ('SERPENTE CASCAVEL', 'Crotalus durissus', 'RÉPTEIS', 4, 4, 0, 0, 0),
  ('SERPENTE COBRA CIPÓ', 'Chironius bicarinatus', 'RÉPTEIS', 2, 2, 0, 0, 0),
  ('SERPENTE CORAL VERDADEIRA', 'Micrurus lemniscatus', 'RÉPTEIS', 2, 2, 0, 0, 0),
  ('SERPENTE CORRE CAMPO', 'Thamnodynastes pallidus', 'RÉPTEIS', 3, 2, 0, 1, 0),
  ('SERPENTE JIBOIA', 'Boa constrictor', 'RÉPTEIS', 6, 6, 0, 0, 0)
) AS t(nome_popular, nome_cientifico, classe_taxonomica, quantidade_resgates, quantidade_solturas, quantidade_obitos, quantidade_feridos, quantidade_filhotes)
GROUP BY nome_popular, nome_cientifico, classe_taxonomica;

-- SETEMBRO 2025
INSERT INTO fat_resgates_diarios_2025_especies (data_ocorrencia, mes, nome_popular, nome_cientifico, classe_taxonomica, quantidade_resgates, quantidade_solturas, quantidade_obitos, quantidade_feridos, quantidade_filhotes)
SELECT 
  '2025-09-01'::date,
  'Setembro',
  nome_popular,
  nome_cientifico,
  classe_taxonomica,
  SUM(quantidade_resgates),
  SUM(quantidade_solturas),
  SUM(quantidade_obitos),
  SUM(quantidade_feridos),
  SUM(quantidade_filhotes)
FROM (VALUES
  ('BEM-TE-VI', 'Pitangus sulphuratus', 'AVES', 6, 0, 0, 4, 2),
  ('CARCARÁ', 'Caracara plancus', 'AVES', 2, 1, 0, 1, 0),
  ('CORUJA BURAQUEIRA', 'Athene cunicularia', 'AVES', 8, 2, 0, 6, 0),
  ('CORUJA CABURÉ', 'Glaucidium brasilianum', 'AVES', 2, 0, 0, 1, 1),
  ('CORUJA SUINDARA', 'Tyto furcata', 'AVES', 1, 0, 0, 1, 0),
  ('CORUJINHA DA MATA', 'Megascops choliba', 'AVES', 1, 1, 0, 0, 0),
  ('CURICACA', 'Theristicus caudatus', 'AVES', 2, 1, 0, 1, 0),
  ('FRANGO D''ÁGUA', 'Gallinula galeata', 'AVES', 2, 0, 0, 2, 0),
  ('JOÃO DE BARRO', 'Furnarius rufus', 'AVES', 2, 1, 0, 1, 0),
  ('MARRECO', 'Anas platyrhynchos domesticus', 'AVES', 4, 0, 0, 4, 0),
  ('MARITACA', 'Pionus maximiliani', 'AVES', 3, 1, 0, 2, 0),
  ('PAPAGAIO VERDADEIRO', 'Amazona aestiva', 'AVES', 3, 0, 0, 2, 0),
  ('PERIQUITO DO ENCONTRO', 'Brotogeris chiriri', 'AVES', 15, 0, 0, 12, 3),
  ('PERIQUITO MARACANÃ', 'Psittacara leucophthalmus', 'AVES', 2, 0, 0, 2, 0),
  ('PERIQUITO REI', 'Eupsittula aurea', 'AVES', 1, 0, 0, 1, 0),
  ('PICA-PAU', 'Campephilus robustus', 'AVES', 3, 0, 0, 3, 0),
  ('POMBA VERDADEIRA', 'Patagioenas picazuro', 'AVES', 2, 0, 0, 1, 1),
  ('QUERO-QUERO', 'Vanellus chilensis', 'AVES', 2, 1, 0, 1, 0),
  ('ROLINHA CINZENTA', 'Columbina passerina', 'AVES', 3, 0, 0, 2, 1),
  ('ROLINHA-ROXA', 'Columbina talpacoti', 'AVES', 2, 0, 0, 2, 0),
  ('SABIÁ-DO-CAMPO', 'Mimus saturninus', 'AVES', 2, 1, 0, 1, 0),
  ('SABIÁ LARANJEIRA', 'Turdus rufiventris', 'AVES', 3, 0, 0, 1, 1),
  ('SUIRIRI-CAVALEIRO', 'Tyrannidae', 'AVES', 1, 0, 0, 1, 0),
  ('URUBU', 'Coragyps atratus', 'AVES', 5, 3, 0, 1, 1),
  ('URUTAU', 'Nyctibius griseus', 'AVES', 1, 1, 0, 0, 0),
  ('CAPIVARA', 'Hydrochoerus hydrochaeris', 'MAMÍFEROS', 6, 4, 0, 2, 0),
  ('CUICA VERDADEIRO', 'Philander opossum', 'MAMÍFEROS', 1, 0, 0, 1, 0),
  ('CUTIA', 'Dasyprocta leporina', 'MAMÍFEROS', 1, 1, 0, 0, 0),
  ('FURÃO', 'Mustela putorius furo', 'MAMÍFEROS', 2, 1, 0, 1, 0),
  ('MACACO BUGIO/GUARIBA', 'Alouatta guariba', 'MAMÍFEROS', 1, 0, 0, 1, 0),
  ('MACACO SAGUI', 'Callithrix jacchus', 'MAMÍFEROS', 3, 1, 0, 2, 0),
  ('MACACO SAGUI DO TUFO PRETO', 'Callithrix pennicillata', 'MAMÍFEROS', 4, 0, 0, 4, 0),
  ('PORCO ESPINHO', 'Coendou prehensilis', 'MAMÍFEROS', 2, 1, 0, 1, 0),
  ('QUATI', 'Nasua nasua', 'MAMÍFEROS', 1, 0, 0, 1, 0),
  ('SARUÊ', 'Didelphis albiventris', 'MAMÍFEROS', 55, 38, 0, 8, 8),
  ('TAMANDUÁ BANDEIRA', 'Myrmecophaga tridactyla', 'MAMÍFEROS', 1, 0, 0, 0, 0),
  ('TAMANDUÁ MIRIM', 'Tamandua tetradactyla', 'MAMÍFEROS', 2, 1, 0, 1, 0),
  ('TATU GALINHA', 'Dasypus novemcinctus', 'MAMÍFEROS', 2, 1, 0, 1, 0),
  ('CALANGO', 'Cnemidophorus ocellifer', 'RÉPTEIS', 1, 1, 0, 0, 0),
  ('CÁGADO COMUM', 'Mauremys leprosa', 'RÉPTEIS', 1, 0, 1, 0, 0),
  ('JABUTI', 'Chelonoidis carbonaria', 'RÉPTEIS', 3, 2, 0, 1, 0),
  ('SERPENTE BOIPEBA', 'Xenodon merremii', 'RÉPTEIS', 1, 1, 0, 0, 0),
  ('SERPENTE CANINANA', 'Spilotes pullatus', 'RÉPTEIS', 1, 1, 0, 0, 0),
  ('SERPENTE CASCAVEL', 'Crotalus durissus', 'RÉPTEIS', 5, 4, 0, 1, 0),
  ('SERPENTE COBRA CIPÓ', 'Chironius bicarinatus', 'RÉPTEIS', 4, 4, 0, 0, 0),
  ('SERPENTE CORAL FALSA', 'Anilis scytale', 'RÉPTEIS', 2, 2, 0, 0, 0),
  ('SERPENTE CORAL VERDADEIRA', 'Micrurus lemniscatus', 'RÉPTEIS', 2, 2, 0, 0, 0),
  ('SERPENTE CORRE CAMPO', 'Thamnodynastes pallidus', 'RÉPTEIS', 4, 3, 0, 1, 0),
  ('SERPENTE JARARACA VERDADEIRA', 'Bothrops jararaca', 'RÉPTEIS', 2, 2, 0, 0, 0),
  ('SERPENTE JIBOIA', 'Boa constrictor', 'RÉPTEIS', 10, 10, 0, 0, 0),
  ('TARTARUGA', 'Caretta caretta', 'RÉPTEIS', 1, 1, 0, 0, 0),
  ('TEIÚ', 'Tupinambis merianae', 'RÉPTEIS', 2, 2, 0, 0, 0)
) AS t(nome_popular, nome_cientifico, classe_taxonomica, quantidade_resgates, quantidade_solturas, quantidade_obitos, quantidade_feridos, quantidade_filhotes)
GROUP BY nome_popular, nome_cientifico, classe_taxonomica;